@alloy => Exclude Year in Art slugs
artsy/artsy-eigen-web-association pull request #3
Opened 2016-12-13 17:20 UTC by kanaabe

This makes use of NOT to exclude certain articles from being redirected to the iOS app.

2016-12-13 17:48 UTC, alloy requested changes

2016-12-13 17:48 UTC, alloy commented on apple-app-site-association.json
> +                   "NOT /article/article/artsy-editorial-the-top-emerging-artists-of-2016",
What'a with the double '/article' pefix?

2016-12-13 17:48 UTC, alloy commented on apple-app-site-association.json
> +                   "NOT /article/artsy-editorial-the most-influential-living-artists-of-2016",
Should that white space be a hyphen?

2016-12-13 18:29 UTC, kanaabe commented on apple-app-site-association.json
> +                   "NOT /article/article/artsy-editorial-the-top-emerging-artists-of-2016",
Sorry both my bad -- 🙈

2016-12-13 19:29 UTC, alloy commented
No worries! That's what reviews are for 👍

2016-12-13 19:29 UTC, merged

2021-11-02 14:14 UTC, artsyit commented
<!-- GITHUB_RELEASE COMMENT: released -->
:rocket: PR was released in [`v1.1.0`](https://github.com/artsy/artsy-eigen-web-association/releases/tag/v1.1.0) :rocket: